=== belkacemlahouel/LO43_SmallWorld/data/save/structure.dtd
<!ELEMENT SmallWorld (board)>
<!ELEMENT board (tribe*,case*)>
<!ELEMENT tribe EMPTY>
<!ELEMENT case (ressource*, individual*)>
<!ELEMENT ressource EMPTY>
<!ELEMENT individual EMPTY>

<!ATTLIST board l CDATA #REQUIRED
				w CDATA #REQUIRED>
<!ATTLIST tribe 	x CDATA #REQUIRED
					y CDATA #REQUIRED
					type (human|robot|bee) #REQUIRED>
<!ATTLIST case 	x CDATA #REQUIRED
				y CDATA #REQUIRED>
<!ATTLIST ressource type CDATA #REQUIRED
					life CDATA "100">
<!ATTLIST individual  	type (human|robot|bee) #REQUIRED
						life CDATA "100"
						team CDATA #REQUIRED>

=== belkacemlahouel/LO43_SmallWorld/data/save/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SmallWorld SYSTEM "structure.dtd">
<SmallWorld>
  <board l="50" w="30">
    <tribe x="36" y="25" type="Human" />
    <tribe x="7" y="22" type="Robot" />
    <tribe x="10" y="5" type="Bee" />
    <case x="2" y="4">
      <ressource type="plutonium" life="100" />
    </case>
    <case x="2" y="6">
      <ressource type="rock" life="100" />
    </case>
    <case x="3" y="13">
      <ressource type="metal" life="100" />
    </case>
    <case x="5" y="2">
      <ressource type="food" life="100" />
    </case>
    <case x="7" y="14">
      <ressource type="wood" life="100" />
      <individual type="robot" life="50" team="2" />
      <individual type="robot" life="50" team="2" />
      <individual type="robot" life="50" team="2" />
    </case>
    <case x="10" y="10">
      <ressource type="rock" life="100" />
      <individual type="bee" life="100" team="3" />
      <individual type="bee" life="100" team="3" />
      <individual type="bee" life="100" team="3" />
      <individual type="bee" life="100" team="3" />
    </case>
    <case x="13" y="14">
      <ressource type="food" life="100" />
    </case>
    <case x="14" y="8">
      <ressource type="wood" life="100" />
    </case>
    <case x="20" y="16">
      <ressource type="metal" life="100" />
    </case>
    <case x="22" y="27">
      <ressource type="plutonium" life="100" />
    </case>
    <case x="33" y="27">
      <ressource type="plutonium" life="100" />
      <individual type="human" life="100" team="1" />
      <individual type="human" life="100" team="1" />
      <individual type="human" life="100" team="1" />
    </case>
    <case x="36" y="0">
      <ressource type="metal" life="100" />
    </case>
    <case x="36" y="2">
      <ressource type="food" life="100" />
    </case>
    <case x="47" y="9">
      <ressource type="wood" life="100" />
      <ressource type="rock" life="100" />
    </case>
  </board>
</SmallWorld>

=== belkacemlahouel/LO43_SmallWorld/data/save/test_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SmallWorld SYSTEM "structure.dtd">
<SmallWorld>
  <board l="60" w="60">
    <tribe x="25" y="21" type="robot" />
    <tribe x="8" y="9" type="human" />
    <tribe x="30" y="2" type="bee" />
    <case x="2" y="38">
      <ressource type="wood" life="100" />
    </case>
    <case x="2" y="45">
      <ressource type="wood" life="100" />
    </case>
    <case x="3" y="48">
      <ressource type="wood" life="100" />
    </case>
    <case x="4" y="31">
      <ressource type="rock" life="100" />
    </case>
    <case x="4" y="53">
      <ressource type="wood" life="100" />
    </case>
    <case x="5" y="12">
      <ressource type="wood" life="86" />
      <individual type="human" life="100" team="2" />
      <individual type="human" life="100" team="2" />
      <individual type="human" life="100" team="2" />
      <individual type="human" life="100" team="2" />
      <individual type="human" life="100" team="2" />
      <individual type="human" life="10" team="2" />
    </case>
    <case x="5" y="43">
      <ressource type="wood" life="100" />
    </case>
    <case x="6" y="39">
      <ressource type="wood" life="100" />
    </case>
    <case x="7" y="47">
      <ressource type="wood" life="100" />
    </case>
    <case x="7" y="50">
      <ressource type="wood" life="100" />
    </case>
    <case x="8" y="32">
      <ressource type="rock" life="100" />
    </case>
    <case x="9" y="54">
      <ressource type="wood" life="100" />
    </case>
    <case x="10" y="40">
      <ressource type="wood" life="100" />
    </case>
    <case x="10" y="43">
      <ressource type="wood" life="100" />
    </case>
    <case x="10" y="46">
      <ressource type="wood" life="100" />
    </case>
    <case x="10" y="49">
      <ressource type="wood" life="100" />
    </case>
    <case x="14" y="43">
      <ressource type="wood" life="12" />
      <individual type="robot" life="10" team="1" />
    </case>
    <case x="14" y="46">
      <ressource type="wood" life="100" />
    </case>
    <case x="14" y="50">
      <ressource type="wood" life="56" />
      <individual type="robot" life="10" team="1" />
    </case>
    <case x="15" y="32">
      <ressource type="rock" life="100" />
    </case>
    <case x="15" y="40">
      <ressource type="wood" life="100" />
    </case>
    <case x="20" y="32">
      <ressource type="rock" life="100" />
    </case>
    <case x="25" y="12">
      <individual type="bee" life="100" team="3" />
    </case>
    <case x="25" y="14">
      <ressource type="food" life="56" />
      <individual type="robot" life="30" team="1" />
      <individual type="robot" life="50" team="1" />
      <individual type="robot" life="50" team="1" />
      <individual type="robot" life="50" team="1" />
      <individual type="robot" life="50" team="1" />
      <individual type="robot" life="50" team="1" />
    </case>
    <case x="25" y="33">
      <ressource type="rock" life="100" />
    </case>
    <case x="30" y="33">
      <ressource type="rock" life="100" />
    </case>
    <case x="36" y="34">
      <ressource type="rock" life="100" />
    </case>
    <case x="43" y="34">
      <ressource type="rock" life="56" />
      <individual type="robot" life="10" team="1" />
    </case>
    <case x="49" y="35">
      <ressource type="rock" life="100" />
    </case>
    <case x="55" y="34">
      <ressource type="rock" life="100" />
    </case>
  </board>
</SmallWorld>

=== belkacemlahouel/LO43_SmallWorld/data/save/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SmallWorld SYSTEM "structure.dtd">
<SmallWorld>
  <board l="60" w="60">
	<tribe x = "25" y = "21" type = "robot"/>
	<tribe x = "8" y = "9" type = "human"/>
	<tribe x = "30" y = "2" type = "bee"/>
	
    <case x="5" y="12">
      <ressource type="wood" life="100" />
    </case>
    <case x="8" y="8">
      <individual type="human" team="2" />
    </case>
    <case x="17" y="44">
      <individual type="robot" team="1" />
    </case>
    <case x="25" y="14">
      <ressource type="food" life="100" />
    </case>
    <case x="25" y="22">
      <individual type="robot" team="1" />
    </case>
    <case x="26" y="54">
      <individual type="robot" team="1" />
    </case>
    <case x="31" y="1">
      <individual type="bee" team="3" />
    </case>
    <case x="40" y="42">
      <individual type="robot" team="1" />
	</case>
	 <case x="43" y="42">
      <ressource type="rock" life="10" />
	  <ressource type="wood" life="10" />
	  <ressource type="food" life="10" />
    </case>
  </board>
</SmallWorld>

=== belkacemlahouel/LO43_SmallWorld/data/save/saveT6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SmallWorld SYSTEM "structure.dtd">
<SmallWorld>
  <board l="110" w="72">
    <tribe x="1" y="14" type="human" />
    <case x="14" y="39">
      <individual type="human" life="62" team="1" />
    </case>
    <case x="20" y="47">
      <ressource type="rock" life="100" />
    </case>
    <case x="39" y="14">
      <individual type="human" life="62" team="1" />
      <individual type="human" life="62" team="1" />
    </case>
    <case x="39" y="27">
      <ressource type="rock" life="100" />
    </case>
    <case x="51" y="71">
      <ressource type="wood" life="100" />
    </case>
    <case x="52" y="67">
      <ressource type="metal" life="70" />
    </case>
    <case x="77" y="28">
      <ressource type="metal" life="70" />
    </case>
    <case x="80" y="10">
      <ressource type="wood" life="100" />
    </case>
    <case x="90" y="6">
      <ressource type="food" life="100" />
    </case>
    <case x="91" y="40">
      <ressource type="food" life="100" />
    </case>
    <case x="92" y="56">
      <ressource type="rock" life="100" />
    </case>
    <case x="94" y="15">
      <ressource type="plutonium" life="50" />
    </case>
    <case x="104" y="15">
      <ressource type="metal" life="70" />
    </case>
    <case x="105" y="62">
      <ressource type="food" life="100" />
    </case>
    <case x="106" y="29">
      <ressource type="wood" life="100" />
    </case>
  </board>
</SmallWorld>

=== belkacemlahouel/LO43_SmallWorld/data/save/save.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SmallWorld SYSTEM "structure.dtd">
<SmallWorld>
  <board l="70" w="50">
    <tribe x="50" y="10" type="robot" />
    <tribe x="32" y="7" type="human" />
    <tribe x="2" y="1" type="bee" />
    <tribe x="52" y="35" type="human" />
    <case x="33" y="15">
      <individual type="human" life="60" team="4" />
    </case>
  </board>
</SmallWorld>
