<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>

<!DOCTYPE SmallWorld[
		<!ELEMENT SmallWorld (board)>
		<!ELEMENT board (case*)>
		<!ELEMENT case (ressource*, human*, robot*)>
		<!ELEMENT ressource EMPTY>
		<!ELEMENT human EMPTY>
                <!ELEMENT robot EMPTY>

		<!ATTLIST board l CDATA #REQUIRED
						w CDATA #REQUIRED>
		<!ATTLIST case x CDATA #REQUIRED
						y CDATA #REQUIRED>
		<!ATTLIST ressource name CDATA #REQUIRED
							life CDATA "10">
		<!ATTLIST human life CDATA "10"
						team CDATA #REQUIRED>
		<!ATTLIST robot life CDATA "10"
						team CDATA #REQUIRED>
		
]>

<SmallWorld>
	<board l="60" w="60">
		<case x="8" y="8">
			<ressource name="rock" life="15" />
			<human life="15" team = "2"/>
		</case>
		<case x="1" y="2">
			<robot life="15" team = "1"/>
		</case>
		<case x="5" y="12">
			<ressource name="tree" life="10"/>
		</case>
		<case x="25" y="14">
			<ressource name="house" life="10"/>
		</case>
	</board>
</SmallWorld>
