<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>

<!DOCTYPE SmallWorld[
		<!ELEMENT SmallWorld (board)>
		<!ELEMENT board (case*)>
		<!ELEMENT case (ressource*, individual*)>
		<!ELEMENT ressource EMPTY>
		<!ELEMENT individual EMPTY>

		<!ATTLIST board l CDATA #REQUIRED
						w CDATA #REQUIRED>
		<!ATTLIST case x CDATA #REQUIRED
						y CDATA #REQUIRED>
		<!ATTLIST ressource type (metal|food|wood|plutonium|rock) #REQUIRED
							life CDATA "10">
		<!ATTLIST individual  type (human|robot) #REQUIRED
							team CDATA #REQUIRED>
		
]>

<SmallWorld>
	<board l="60" w="60">
		<case x="8" y="8">
			<ressource type="rock" life="15" />
			<individual type = "human" team = "2"/>
		</case>
		<case x="50" y="50">
			<individual type = "robot" team = "1"/>
		</case>
		<case x="5" y="12">
			<ressource type="wood" life="10"/>
		</case>
		<case x="25" y="14">
			<ressource type="food" life="10"/>
		</case>
		<case x="50" y="1">
			<individual type="bee" team="3"/>
		</case>
		<case x="20" y="20">
			<ressource name="rock" life="100" />
		</case>
		<case x="30" y="30">
			<ressource name="rock" life="100"/>
		</case>
	</board>
</SmallWorld>
